[workspace]
members = ["crates/backend", "crates/frontend"]

[workspace.package]
version = "0.1.2"
edition = "2021"
authors = ["Mike Lloyd"]
description = "Web app for tracking key inventory and assignments"
