version: "3"

services:
  app:
    image: keymaster:latest
    restart: always
    depends_on:
      - postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres
      KEYMASTER_ADMIN_USER: ${KEYMASTER_ADMIN_USER}
      KEYMASTER_ADMIN_PASS: ${KEYMASTER_ADMIN_PASS}
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
